#!/bin/sh
if [ -z "$1" ]; then
	LAST_N=1
else
	LAST_N=$1
fi
vim $(grep 'created_at' posts/*.textile | awk -F: '{ print $3, "---", $1 }' | sort | awk -F--- '{ print $2 }' | tail -n${LAST_N} | head -n1)
